"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeType = exports.nodeToType = exports.clearNodes = exports.analyzeStructure = exports.toSingularAction = exports.generateSingle = exports.generateReducersForStore = exports.generateCollection = exports.initialFetch = exports.clearStore = exports.single_all = exports.generateActionsForStore = exports.collection_all = exports.generateActionTypesForStore = exports.generateActionTypesDictionaryForStore = void 0;
var actionTypes_1 = require("./actionTypes");
Object.defineProperty(exports, "generateActionTypesDictionaryForStore", { enumerable: true, get: function () { return actionTypes_1.generateActionTypesDictionaryForStore; } });
Object.defineProperty(exports, "generateActionTypesForStore", { enumerable: true, get: function () { return actionTypes_1.generateActionTypesForStore; } });
var actions_1 = require("./actions");
Object.defineProperty(exports, "collection_all", { enumerable: true, get: function () { return actions_1.collection_all; } });
Object.defineProperty(exports, "generateActionsForStore", { enumerable: true, get: function () { return actions_1.generateActionsForStore; } });
Object.defineProperty(exports, "single_all", { enumerable: true, get: function () { return actions_1.single_all; } });
var clear_1 = require("./clear");
Object.defineProperty(exports, "clearStore", { enumerable: true, get: function () { return clear_1.clearStore; } });
var getAll_1 = require("./getAll");
Object.defineProperty(exports, "initialFetch", { enumerable: true, get: function () { return getAll_1.initialFetch; } });
var reducers_1 = require("./reducers");
Object.defineProperty(exports, "generateCollection", { enumerable: true, get: function () { return reducers_1.generateCollection; } });
Object.defineProperty(exports, "generateReducersForStore", { enumerable: true, get: function () { return reducers_1.generateReducersForStore; } });
Object.defineProperty(exports, "generateSingle", { enumerable: true, get: function () { return reducers_1.generateSingle; } });
var singular_1 = require("./singular");
Object.defineProperty(exports, "toSingularAction", { enumerable: true, get: function () { return singular_1.toSingularAction; } });
var structure_1 = require("./structure");
Object.defineProperty(exports, "analyzeStructure", { enumerable: true, get: function () { return structure_1.analyzeStructure; } });
Object.defineProperty(exports, "clearNodes", { enumerable: true, get: function () { return structure_1.clearNodes; } });
Object.defineProperty(exports, "nodeToType", { enumerable: true, get: function () { return structure_1.nodeToType; } });
var types_1 = require("./types/types");
Object.defineProperty(exports, "NodeType", { enumerable: true, get: function () { return types_1.NodeType; } });
